name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '.github/requirements.txt'

      - name: Install Python dependencies
        run: pip install -r .github/requirements.txt

      - name: Install NPM dependencies
        run: npm install -g codecov
      
      - name: Test the extension
        run: |
          python -m pip install --upgrade -v -e ".[test, examples, docs]"
          yarn run lint:check

          pytest
          yarn run test
