name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '.github/requirements.txt'

      - name: Install Python dependencies
        run: pip install -r .github/requirements.txt

      - name: Install NPM dependencies
        run: npm install -g codecov
      
      - name: Test the extension
        run: |
          pip install --upgrade -v -e ".[test, examples, docs]"
          yarn run lint:check

          pytest
          yarn run test

      - name: Build wheel
        run: python -m build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          if-no-files-found: error

      - name: Remove files not needed for pypi
        run: rm dist/index.js*

      - uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
